version: '3.8'

services:
  crm-backend:
    build: .
    container_name: crm-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
